server:
  port: 8085
spring:
  application:
    name: terminal-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.185:8848
        service: terminal-service
        namespace: 1e90921e-70cf-4745-87ed-dd165319ff3a
        group: DEFAULT_GROUP
        username: Nan
        password: Nan12091209
        access-key: nan_nacos
        secret-key: nanproduced
        register-enabled: true
        # 类似长连接监听服务端信息变化的功能
        watch:
          enabled: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000

  datasource:
    username: root
    password: Nan12091209
    url: jdbc:mysql://192.168.1.185:3306/nan_test?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 10000
      idle-timeout: 180000
      max-lifetime: 600000
  
  # 本地Redis
  data:
    redis:
      host: 192.168.1.185
      port: 6379
      database: 1
      password: Nan12091209
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 1000ms
    mongodb:
      host: 192.168.1.185
      port: 27017
      database: nan_test
      username: root
      password: Nan12091209
      authentication-database: admin
      auto-index-creation: true

# 本地环境日志配置 - 更详细的日志便于调试
logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
    io.netty: DEBUG
    org.nan.cloud.terminal: DEBUG
    # WebSocket相关日志
    org.springframework.web.socket: DEBUG

# 本地环境监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  # Zipkin Reporter 的专属配置
  zipkin:
    tracing:
      # 默认 auto-config 会把 span 发到这个端点
      endpoint: http://192.168.1.185:9411/api/v2/spans
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true

