# LED设备终端通信服务基础配置
# 针对10k并发WebSocket连接优化

server:
  port: 8082
  # Tomcat连接器优化 - 支持高并发连接
  tomcat:
    # 最大连接数，支持10k并发
    max-connections: 10000
    # 接受队列大小，避免连接被拒绝
    accept-count: 2000
    # 最大工作线程数
    threads:
      max: 500
      min-spare: 50
    # 连接超时时间(毫秒)
    connection-timeout: 20000
    # Keep-Alive超时时间(毫秒)
    keep-alive-timeout: 60000
    # 最大Keep-Alive请求数
    max-keep-alive-requests: 1000

spring:
  application:
    name: terminal-service
  
  # Spring Boot配置优化
  main:
    # 允许循环依赖，提升启动性能
    allow-circular-references: true
    # 懒加载Bean，减少启动时间
    lazy-initialization: false
  
  # 数据源配置 - HikariCP高性能连接池
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.185:3306/led_device_platform?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    
    # HikariCP连接池优化配置
    hikari:
      # 最大连接数，支持高并发数据库访问
      maximum-pool-size: 50
      # 最小空闲连接数
      minimum-idle: 10
      # 连接超时时间(毫秒) - 30秒
      connection-timeout: 30000
      # 空闲连接存活时间(毫秒) - 10分钟
      idle-timeout: 600000
      # 连接最大生命周期(毫秒) - 30分钟
      max-lifetime: 1800000
      # 连接池名称
      pool-name: TerminalServiceHikariCP
      # 连接测试查询
      connection-test-query: SELECT 1
      # 验证连接有效性的超时时间(毫秒)
      validation-timeout: 5000
      # 是否自动提交
      auto-commit: true
      # 连接初始化SQL
      connection-init-sql: SET NAMES utf8mb4
  
  # Redis配置 - Lettuce高性能客户端
  data:
    redis:
      # Redis服务器配置
      host: 192.168.1.185
      port: 6379
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 5000ms
      
      # Lettuce连接池配置
      lettuce:
        pool:
          # 最大连接数，支持高并发Redis访问
          max-active: 200
          # 最大空闲连接数
          max-idle: 50
          # 最小空闲连接数
          min-idle: 10
          # 连接获取超时时间
          max-wait: 3000ms
        # 关闭连接超时时间
        shutdown-timeout: 100ms
  
    # MongoDB配置 - 异步响应式驱动
    mongodb:
      uri: mongodb://192.168.1.185:27017/led_device_platform
      database: led_device_platform
      # 连接池配置
      options:
        # 最大连接数
        max-connection-pool-size: 100
        # 最小连接数
        min-connection-pool-size: 10
        # 连接最大空闲时间(毫秒)
        max-connection-idle-time: 600000
        # 连接最大生命周期(毫秒)
        max-connection-life-time: 1800000
        # 连接超时时间(毫秒)
        connect-timeout: 10000
        # Socket超时时间(毫秒)
        socket-timeout: 30000
        # 服务器选择超时时间(毫秒)
        server-selection-timeout: 5000

  # 云服务发现配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.185:8848
        namespace: 1e90921e-70cf-4745-87ed-dd165319ff3a
        group: DEFAULT_GROUP
        service: terminal-service
        # 实例权重，用于负载均衡
        weight: 1
        # 健康检查配置
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        ip-delete-timeout: 30000
      config:
        server-addr: 192.168.1.185:8848
        namespace: 1e90921e-70cf-4745-87ed-dd165319ff3a
        group: DEFAULT_GROUP
        file-extension: yml
        # 动态配置刷新
        refresh-enabled: true

# MyBatis Plus配置
mybatis-plus:
  # Mapper XML扫描路径
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体类包路径
  type-aliases-package: org.nan.cloud.terminal.**.entity
  configuration:
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true
    # 缓存配置
    cache-enabled: true
    # 延迟加载配置
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    # 日志配置
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# WebSocket服务配置
websocket:
  # WebSocket端点路径
  endpoint: /terminal/ws
  # 心跳配置
  heartbeat:
    # 心跳间隔(秒) - LED设备55秒心跳
    interval: 55
    # 心跳超时时间(秒)
    timeout: 110
  # 连接管理配置
  connection:
    # 最大连接数
    max-connections: 10000
    # 分片数量，减少锁竞争
    shard-count: 16
    # 连接超时时间(秒)
    timeout: 300

# Netty性能调优配置
netty:
  # Boss线程数(通常为CPU核心数)
  boss-threads: 2
  # Worker线程数(通常为CPU核心数 * 2)
  worker-threads: 16
  # 内存分配器配置
  allocator:
    # 使用池化的直接内存分配器
    type: pooled
    # 直接内存使用堆外内存
    prefer-direct: true
  # 缓冲区配置
  buffer:
    # 接收缓冲区大小(字节)
    receive-buffer-size: 65536
    # 发送缓冲区大小(字节)
    send-buffer-size: 65536
  # Socket配置
  socket:
    # TCP连接队列大小，支持高并发连接
    backlog: 32768
    # 启用TCP_NODELAY，减少延迟
    tcp-nodelay: true
    # 启用SO_REUSEADDR，端口复用
    so-reuseaddr: true
    # 启用SO_KEEPALIVE，保持连接
    so-keepalive: true

# 认证配置
security:
  # Basic Auth配置
  basic:
    # 认证缓存TTL(分钟)
    cache-ttl: 30
    # 最大登录尝试次数
    max-attempts: 5
    # 锁定时间(分钟)
    lockout-duration: 15
  # 无状态会话配置
  session:
    creation-policy: stateless

# 性能监控配置
management:
  endpoints:
    web:
      exposure:
        # 暴露所有监控端点
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      # 显示详细健康信息
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      # Prometheus监控导出
      prometheus:
        enabled: true
    # JVM监控配置
    jvm:
      memory:
        enabled: true
      gc:
        enabled: true
      threads:
        enabled: true
    # 系统监控配置
    system:
      cpu:
        enabled: true
      disk:
        enabled: true
      process:
        enabled: true

# 日志配置
logging:
  level:
    root: INFO
    # Spring框架日志级别
    org.springframework: INFO
    # MyBatis日志级别
    org.mybatis: DEBUG
    # Netty日志级别
    io.netty: INFO
    # 应用日志级别
    org.nan.cloud.terminal: DEBUG
  pattern:
    # 控制台日志格式
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{50} - %msg%n"
    # 文件日志格式
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{50} - %msg%n"
  file:
    # 日志文件路径
    name: logs/terminal-service.log
    # 日志文件最大大小
    max-size: 100MB
    # 日志文件最大历史数
    max-history: 30
    # 日志文件总大小限制
    total-size-cap: 3GB

# 自定义业务配置
terminal:
  # 设备配置
  device:
    # 设备指令超时时间(秒)
    command-timeout: 30
    # 设备状态更新间隔(秒)
    status-update-interval: 60
    # 设备离线判断时间(秒)
    offline-threshold: 120
  
  # 文件管理配置
  file:
    # 文件上传路径
    upload-path: /data/terminal-files
    # 支持的文件类型
    allowed-types: jpg,jpeg,png,gif,mp4,avi,mov,pdf,doc,docx,xls,xlsx
    # 单个文件最大大小(MB)
    max-file-size: 100
    # 总文件大小限制(GB)
    total-size-limit: 10
    # MD5校验开关
    md5-check-enabled: true
  
  # 缓存配置
  cache:
    # 设备状态缓存TTL(秒)
    device-status-ttl: 300
    # 指令缓存TTL(秒)
    command-ttl: 1800
    # 用户认证缓存TTL(秒)
    auth-ttl: 1800