server:
  port: 8082
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.185:8848
        service: gateway-server
        namespace: 1e90921e-70cf-4745-87ed-dd165319ff3a
        group: DEFAULT_GROUP
        username: Nan
        password: Nan12091209
        access-key: nan_nacos
        secret-key: nanproduced
        register-enabled: true
        # 类似长连接监听服务端信息变化的功能
        watch:
          enabled: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 30s
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/core/api/**

  datasource:
    username: root
    password: Nan12091209
    url: jdbc:mysql://192.168.1.185:3306/nan_test?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&allowPublicKeyRetrieval=true
  data:
    redis:
      host: 192.168.1.185
      port: 6379
      database: 1
      password: Nan12091209
      timeout: 3000
      lettuce:
        pool:
          max-active: 50
          max-idle: 48
          min-idle: 0
          max-wait: 5s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server/rsa/publicKey
      client:
        registration:
          gateway-server:
            client-id: gateway-server-client
            client-secret: nanproduced
            authorization-grant-type: authorization_code
            provider: auth-server
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
        provider:
          auth-server:
            issuer-uri: http://192.168.1.222:8081

casbin:
  model: classpath:casbin/model.conf
  watcher-type: redis
  watcher-lettuce-redis-type: standalone
  store-type: jdbc
  initialize-schema: create
  table-name: rbac_casbin_rules
  policy-topic: RBAC_CASBIN_POLICY_TOPIC

springdoc:
  swagger-ui:
    urls:
        - name: core-service
          url: /core/api/v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.alibaba.nacos: DEBUG

customer:
  security:
    ignore:
      urls:
