# 缓存配置
cache:
  # 本地缓存配置 (Caffeine)
  local:
    enabled: true
    maximum-size: 10000
    expire-after-write: 30m
    expire-after-access: 10m
    refresh-after-write: 20m
    record-stats: true
  
  # Redis分布式缓存配置
  redis:
    enabled: true
    key-prefix: "core:cache:"
    default-ttl: 30m
    enable-keyspace-notifications: true
  
  # 缓存同步配置
  sync:
    enabled: true
    topic: "cache:sync"
    timeout: 5s

# Redis配置
spring:
  data:
    redis:
      # Redis服务器配置
      host: 192.168.1.185
      port: 6379
      password: 
      database: 0
      timeout: 6000ms
      
      # 连接池配置
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

# 缓存相关日志配置
logging:
  level:
    org.nan.cloud.core.infrastructure.cache: DEBUG
    com.github.benmanes.caffeine: INFO