server:
  port: 8081
spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.185:8848
        service: auth-server
        namespace: 1e90921e-70cf-4745-87ed-dd165319ff3a
        group: DEFAULT_GROUP
        username: Nan
        password: Nan12091209
        access-key: nan_nacos
        secret-key: nanproduced
        register-enabled: true
        # 类似长连接监听服务端信息变化的功能
        watch:
          enabled: true
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
  datasource:
    username: root
    password: Nan12091209
    url: jdbc:mysql://192.168.1.185:3306/nan_test?zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&allowPublicKeyRetrieval=true
  security:
    oauth2:
      auth-server:
        issuer: 192.168.1.222:8081

mybatis-plus:
  # xml文件位置
  mapper-locations: classpath:org.nan.cloud.auth.mapper/*.xml

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.alibaba.nacos: DEBUG

custom:
  security:
    jwt-alias: demo-jwt
    jwt-key: Nan12091209