server:
  port: 8086

spring:
  application:
    name: file-service

  config:
    import:
      - optional:nacos:file-service-dev.yml?group=DEFAULT_GROUP&refresh=true

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.185:8848
        namespace: 1e90921e-70cf-4745-87ed-dd165319ff3a
        group: DEFAULT_GROUP
        username: Nan
        password: Nan12091209
        access-key: nan_nacos
        secret-key: nanproduced
        fail-fast: false
      config:
        server-addr: 192.168.1.185:8848
        namespace: 1e90921e-70cf-4745-87ed-dd165319ff3a
        group: DEFAULT_GROUP
        username: Nan
        password: Nan12091209
        access-key: nan_nacos
        secret-key: nanproduced
        timeout: 5000
        config-long-poll-timeout: 1000
        config-retry-time: 100000
        max-retry: 3
        refresh-enabled: true
        file-extension: yml

  # RabbitMQ配置
  rabbitmq:
    host: 192.168.1.185
    port: 5672
    username: admin
    password: Nan12092109
    virtual-host: /led-platform-dev
    connection-timeout: 15000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.185:3306/led_platform_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Nan12091209
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: FileServiceHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  # Redis配置
  data:
    redis:
      host: 192.168.1.185
      port: 6379
      database: 1  # file-service专用数据库
      timeout: 3000ms
      password: 
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
    
    # MongoDB配置 - 文件元数据存储
    mongodb:
      host: 192.168.1.185
      port: 27017
      database: led-platform-files-dev
      username: 
      password: 

  # 异步任务配置
  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 200
        keep-alive: 60s
      thread-name-prefix: file-upload-

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*.xml

# 文件存储配置
file:  
  storage:
    default-strategy: LOCAL
    # 本地存储配置
    local:
      base-path: C:/Users/nanpr/javaProject/filePath
      temp-path: C:/Users/nanpr/javaProject/filePath/temp
      thumbnail-base-path: C:/Users/nanpr/javaProject/filePath/thumbnails
      url-prefix: http://localhost:8086/files
      max-file-size: 5368709120  # 5GB
      
    # 云存储配置 (阿里云OSS)
    oss:
      endpoint: https://oss-cn-hangzhou.aliyuncs.com
      access-key-id: 
      access-key-secret: 
      bucket-name: led-platform-files
      url-prefix: https://led-platform-files.oss-cn-hangzhou.aliyuncs.com
      
  # 缩略图配置
  thumbnail:
    enabled: true
    sizes:
      - "150x150"
      - "300x300" 
      - "600x600"
    quality: 0.8
    format: jpg
    # 视频缩略图配置
    video:
      enabled: true
      frame-rate: 1.0
      gpu-acceleration: true
      
  # 转码配置
  transcoding:
    # FFmpeg配置
    ffmpeg:
      path: "/usr/local/bin/ffmpeg"
      threads: 8
      timeout: 3600
      enable-gpu: true
    
    # 临时文件配置
    temp:
      dir: "C:/Users/nanpr/javaProject/filePath/temp/transcoding"
    
    # 队列配置
    queue:
      max-concurrent-tasks: 3
      max-queue-size: 100
      priority-enabled: true
    
    # 转码预设配置
    presets:
      # LED高分辨率预设 - 适用于户外大屏LED (4K)
      - id: "led-4k"
        name: "LED 4K高分辨率"
        video-codec: "libx264"
        audio-codec: "aac"
        width: 3840
        height: 2160
        video-bitrate: 8000
        audio-bitrate: 192
        crf: 20
        preset: "medium"
        
      # LED全高清预设 - 适用于室内LED显示 (1080p)
      - id: "led-1080p"
        name: "LED 1080p标准"
        video-codec: "libx264"
        audio-codec: "aac"
        width: 1920
        height: 1080
        video-bitrate: 4000
        audio-bitrate: 128
        crf: 22
        preset: "medium"
        
      # LED高清预设 - 适用于中等尺寸LED (720p)
      - id: "led-720p"
        name: "LED 720p高清"
        video-codec: "libx264"
        audio-codec: "aac"
        width: 1280
        height: 720
        video-bitrate: 2500
        audio-bitrate: 128
        crf: 24
        preset: "medium"
        
      # LED标清预设 - 适用于小尺寸LED显示
      - id: "led-480p"
        name: "LED 480p标清"
        video-codec: "libx264"
        audio-codec: "aac"
        width: 854
        height: 480
        video-bitrate: 1200
        audio-bitrate: 96
        crf: 26
        preset: "medium"
        
      # LED超高质量预设 - 适用于重要展示内容
      - id: "led-premium"
        name: "LED超高质量"
        video-codec: "libx264"
        audio-codec: "aac"
        width: 1920
        height: 1080
        video-bitrate: 6000
        audio-bitrate: 256
        crf: 18
        preset: "slow"
        
      # LED经济预设 - 节省存储空间
      - id: "led-economy"
        name: "LED经济模式"
        video-codec: "libx264"
        audio-codec: "aac"
        width: 1280
        height: 720
        video-bitrate: 1500
        audio-bitrate: 96
        crf: 28
        preset: "fast"
        
      # LED快速预设 - 快速转码
      - id: "led-fast"
        name: "LED快速转码"
        video-codec: "libx264"
        audio-codec: "aac"
        width: 1920
        height: 1080
        video-bitrate: 3000
        audio-bitrate: 128
        crf: 25
        preset: "ultrafast"
        
      # LED宽屏预设 - 适用于16:10显示比例
      - id: "led-widescreen"
        name: "LED宽屏显示"
        video-codec: "libx264"
        audio-codec: "aac"
        width: 1920
        height: 1200
        video-bitrate: 4500
        audio-bitrate: 128
        crf: 22
        preset: "medium"
        
  # 文件验证配置
  validation:
    # 支持的文件类型
    supported-types:
      image: 
        - jpg
        - jpeg
        - png
        - gif
        - bmp
        - webp
        - svg
      video: 
        - mp4
        - avi
        - mov
        - wmv
        - flv
        - mkv
        - webm
      audio: 
        - mp3
        - wav
        - aac
        - flac
        - ogg
      document: 
        - pdf
        - doc
        - docx
        - xls
        - xlsx
        - ppt
        - pptx
        - txt
      archive: 
        - zip
        - rar
        - 7z
        - tar
        - gz
      
    # 文件大小限制 (字节)
    max-file-size:
      image: 10485760      # 10MB
      video: 524288000     # 500MB  
      audio: 52428800      # 50MB
      document: 20971520   # 20MB
      archive: 104857600   # 100MB
      default: 52428800    # 50MB

# Common-MQ配置
mq:
  enabled: true
  auto-startup: true
  exchanges:
    config-location: classpath:rabbitmq/exchanges.json
  producers:
    default:
      retry-times: 3
      retry-interval: 1000
      timeout: 5000
      confirm-callback: true
      return-callback: true

# 日志配置
logging:
  level:
    org.nan.cloud.file: DEBUG
    org.nan.cloud.common.mq: INFO
    org.springframework.amqp: INFO
    org.springframework.web.multipart: DEBUG
    com.baomidou.mybatisplus: DEBUG

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always